[package]
name = "gameboy-rust"
version = "0.1.0"
authors = ["Johan Lindskogen <johan.lindskogen@gmail.com>"]

[dependencies]
bitflags = "1.3.2"
minifb = "0.20"

[lib]
name = "dmg"
path = "src/lib.rs"
