[package]
name = "gameboy-rust"
version = "0.1.0"
authors = ["Johan Lindskogen <johan.lindskogen@gmail.com>"]

[dependencies]
bitflags = "1.3.2"
bit_field = "0.10.1"
minifb = "0.20"
image = "0.24.1"

[lib]
name = "dmg"
path = "src/lib.rs"
